import { environment } from 'src/environments/environment';
const API_URL = environment.apiBaseUrl;

export const AppConfig = {
  USER_KEY : 'user_data',
  pageSize: 10,
  dashBoardPageSize: 6,
  Base_url: API_URL,
  auth: {
    login: `${API_URL}/login`,
    register: `${API_URL}/register`,
    forgotpassword: `${API_URL}/Forgot-password`,
    changePassword: `${API_URL}/change-password`,
    getPermissions: `${API_URL}/getPermissions`,
    notificationMethods: `${API_URL}/notificationMethods`,
    resetpassword: `${API_URL}/Reset-password`,
    getUserProfile: `${API_URL}/getUserProfile`,
    updateUserInfo: `${API_URL}/updateUserInfo`,
    GetUserDeviceId: `${API_URL}/GetUserDeviceId`,
    UpdateUserDeviceId: `${API_URL}/UpdateUserDeviceId`,
    DeleteUserDeviceId: `${API_URL}/DeleteUserDeviceId`,
    AddUserDeviceId: `${API_URL}/AddUserDeviceId`,
    UpdateNotificationSettings: `${API_URL}/updateNotificationSettings`,
    getNotificationSettings: `${API_URL}/getNotificationSettings`,
  },
  tasks: {
    allTasks: `${API_URL}/Task/allTasks`,
    deleteTask: `${API_URL}/Task/deleteTask`,
    updateTask: `${API_URL}/Task/updateTask`,
    addTask: `${API_URL}/Task/addTask`,
    getTasksByRelatedContactId: `${API_URL}/Task/GetTasksByRelatedContactId`,
    getTasksByRelatedJobId: `${API_URL}/Task/GetTasksByRelatedJobId`,
    getTaskStatusCountsByJobIdAsync: `${API_URL}/Task/GetTaskStatusCountsByJobIdAsync`,
    getTaskStatusCountsByContactIdAsync: `${API_URL}/Task/GetTaskStatusCountsByContactIdAsync`,
    getTaskStatusCounts: `${API_URL}/Task/GetTaskStatusCounts`,
  },
  status: {
    allStatuses: `${API_URL}/Status/allStatuses`,
    getStatusesByWorkFlowId: `${API_URL}/Status/getStatusesByWorkFlowId`,
  },
  SubContractor: {
    getsubcontractors: `${API_URL}/SubContractor/getsubcontractors`,
  },
  RelatedContact: {
    getRelatedContactsDropDown: `${API_URL}/RelatedContact/getRelatedContactsDropDown`,
  },
  BussinessHours: {
    Add: `${API_URL}/BussinessHours/Add`,
    Update: `${API_URL}/BussinessHours/Update`,
    Delete: `${API_URL}/BussinessHours/Delete`,
    Getbyid: `${API_URL}/BussinessHours/Getbyid`,
    Pagedbussinesshours: `${API_URL}/BussinessHours/Pagedbussinesshours`,
    Allbussinesshours: `${API_URL}/BussinessHours/Allbussinesshours`,
  },
  Company: {
    PagedCompamnies: `${API_URL}/Company/PagedCompamnies`,
    allCompamnies: `${API_URL}/Company/allCompamnies`,
  },
  DropDown: {
    allDropDownsList: `${API_URL}/DropDown/allDropDownsList`,
    getDropDownChilds: `${API_URL}/DropDown/getDropDownChilds`,
  },
  OfficeLocation: {
    addOfficeLocation: `${API_URL}/OfficeLocation/addOfficeLocation`,
    updateOfficeLocation: `${API_URL}/OfficeLocation/updateOfficeLocation`,
    getOfficeLocationById: `${API_URL}/OfficeLocation/getOfficeLocationById`,
    PagedOfficeLocations: `${API_URL}/OfficeLocation/PagedOfficeLocations`,
    allOfficeLocations: `${API_URL}/OfficeLocation/allOfficeLocations`,
    officelocationsdropdown: `${API_URL}/OfficeLocation/officelocationsdropdown`,
  },
  SalesRepresentative: {
    getsalesrepresentative: `${API_URL}/SalesRepresentative/getsalesrepresentative`,
  },
  States: `${API_URL}/States`,
  TeamMember: {
    add: `${API_URL}/TeamMember/add`,
    update: `${API_URL}/TeamMember/update`,
    disablelogin: `${API_URL}/TeamMember/disablelogin`,
    getteammebers: `${API_URL}/TeamMember/getteammebers`,
    paged: (pageIndex: number,pageSize:number) => `${API_URL}/TeamMember/paged?pageIndex=${pageIndex}&pageSize=${pageSize}`,
    delete: (Id: number) => `${API_URL}/TeamMember/delete?Id=${Id}`,
  },
  
  TimeZone: `${API_URL}/TimeZone`,
  Contact: {
    PagedContacts: `${API_URL}/Contact/PagedContacts`,
    addContact: `${API_URL}/Contact/addContact`,
    allContacts: `${API_URL}/Contact/allContacts`,
    deleteContact: `${API_URL}/Contact/deleteContact`,
    getContactById: `${API_URL}/Contact/getContactById`,
    updateContact: `${API_URL}/Contact/updateContact`,
    updateContactStatusAndWorkflow: `${API_URL}/Contact/updateContactStatusAndWorkflow`,
  },
  WorkFlow: {
    alljobWorkFlows: `${API_URL}/JobWorkFlow/GetAllWorkFlows`,
    alljobWorkFlowsByType: `${API_URL}/JobWorkFlow/allWorkFlowsByType`,
    GetjobWorkFlowById: `${API_URL}/JobWorkFlow/GetWorkFlowById`,
    CreatejobWorkFlow: `${API_URL}/JobWorkFlow/CreateWorkFlow`,
    UpdatejobWorkFlow: `${API_URL}/JobWorkFlow/UpdateWorkFlow`,
  },
  Jobs: {
    CreateJob: `${API_URL}/Jobs/CreateJob`,
    SearchAll: `${API_URL}/Jobs/SearchAll`,
    GetAllJob: `${API_URL}/Jobs/GetAllJob`,
    GetJobById: `${API_URL}/Jobs/GetJobById`,
    UpdateJob: `${API_URL}/Jobs/UpdateJob`,
    GetAllJobByCompanyId: `${API_URL}/Jobs/GetAllJobByCompanyId`,
    GetAllJobWithPagination: `${API_URL}/Jobs/GetAllJobWithPagination`,
    DeleteJob: `${API_URL}/Jobs/DeleteJob`,
    updateJobStatusAndWorkflow: `${API_URL}/Jobs/updateJobStatusAndWorkflow`,

  },
  Events: {
    GetEventById: `${API_URL}/Events/GetEventById`,
    DeleteEvent: `${API_URL}/Events/DeleteEvent`,
    UpdateEvent: `${API_URL}/Events/UpdateEvent`,
    GetEventsByJobId: `${API_URL}/Events/GetEventsByJobId`,
    GetAllEvent: `${API_URL}/Events/GetAllEvent`,
    CreateEvent: `${API_URL}/Events/CreateEvent`,
    GetJobsStatusById: `${API_URL}/Events/GetJobsStatusById`,
    GetAllJobsStatus: `${API_URL}/Events/GetAllJobsStatus`,
  },
  JobStatus: {
    CreateJobStatus: `${API_URL}/JobStatus/CreateJobStatus`,
    UpdateJobStatus: `${API_URL}/JobStatus/UpdateJobStatus`,
    UpdateLeadSource: `${API_URL}/JobStatus/UpdateLeadSource`,
  },
  LeadSource: {
    GetLeadSourceById: `${API_URL}/LeadSource/GetLeadSourceById`,
    GetAllLeadSource: `${API_URL}/LeadSource/GetAllLeadSource`,
    CreateLeadSource: `${API_URL}/LeadSource/CreateLeadSource`,
  },
  Tags: {
    CreateTag: `${API_URL}/Tags/CreateTag`,
    UpdateTag: `${API_URL}/Tags/UpdateTag`,
    GetAllTag: `${API_URL}/Tags/GetAllTag`,
  },
  WorkOrder: {
    GetWorkOrderById: `${API_URL}/WorkOrder/GetWorkOrderById`,
    CreateWorkOrder: `${API_URL}/WorkOrder/CreateWorkOrder`,
    UpdateWorkOrder: `${API_URL}/WorkOrder/UpdateWorkOrder`,
    DeleteWorkOrder: `${API_URL}/WorkOrder/DeleteWorkOrder`,
    GetAllWorkOrder: `${API_URL}/WorkOrder/GetAllWorkOrder`,
    GetWorkOrderByJobId: `${API_URL}/WorkOrder/GetWorkOrderByJobId`,
    updateWorkOrderStatusAndWorkflow: `${API_URL}/WorkOrder/updateWorkOrderStatusAndWorkflow`,

  },
  GlobalWorkFlow: {
    allWorkFlows: `${API_URL}/WorkFlow/allWorkFlows`,
    PagedWorkFlows: `${API_URL}/WorkFlow/PagedWorkFlows`,
    addWorkFlow: `${API_URL}/WorkFlow/addWorkFlow`,
    updateWorkFlow: `${API_URL}/WorkFlow/updateWorkFlow`,
    deleteWorkFlow: `${API_URL}/WorkFlow/deleteWorkFlow`,
    getWorkFlowById: `${API_URL}/WorkFlow/getWorkFlowById`,
    allWorkFlowsByType: `${API_URL}/WorkFlow/allWorkFlowsByType`,
  },
  Notes: {
    GetNoteById: `${API_URL}/Notes/GetNoteById`,
    GetAllNotes: `${API_URL}/Notes/GetAllNotes`,
    CreateNote: `${API_URL}/Notes/CreateNote`,
    UpdateNote: `${API_URL}/Notes/UpdateNote`,
    DeleteNote: `${API_URL}/Notes/DeleteNote`,
  },
  jobsLog: {
    getLogById: `${API_URL}/JobsLogbook/GetLogById`,
    getAllLogs: `${API_URL}/JobsLogbook/GetAllLogs`,
    getLogsByJobId: `${API_URL}/JobsLogbook/GetLogsByJobId`,
    getLogsByWorkOrderId: `${API_URL}/JobsLogbook/GetLogsByWorkOrderId`,
    getLogsByTaskId: `${API_URL}/JobsLogbook/GetLogsByTaskId`,
    getLogsByContactId: `${API_URL}/JobsLogbook/GetLogsByContactId`,
    deleteLog: `${API_URL}/JobsLogbook/DeleteLog`,
    getUserActivityLogs: `${API_URL}/JobsLogbook/GetUserActivityLogs`,
  },
  Photos: {
    GetPhotoById: `${API_URL}/JobPhotos/GetPhotoById`,
    GetPhotosByJobId: `${API_URL}/JobPhotos/GetPhotosByJobId`,
    GetAllPhotos: `${API_URL}/JobPhotos/GetAllPhotos`,
    AddJobPhoto: `${API_URL}/JobPhotos/AddJobPhoto`,
    UpdateJobPhoto: `${API_URL}/JobPhotos/UpdateJobPhoto`,
    DeleteJobPhoto: `${API_URL}/JobPhotos/DeleteJobPhoto`,
    DownloadFiles: `${API_URL}/JobPhotos/DownloadFiles`,
  },
  Boards: {
    GetBoardById: `${API_URL}/Boards/GetBoardById`,
    GetAllBoards: `${API_URL}/Boards/GetAllBoards`,
    GetBoardStatuses: `${API_URL}/Boards/GetBoardStatuses`,
    CreateBoard: `${API_URL}/Boards/CreateBoard`,
    UpdateBoard: `${API_URL}/Boards/UpdateBoard`,
    DeleteBoard: `${API_URL}/Boards/DeleteBoard`,
    CreateFolder: `${API_URL}/Boards/CreateFolder`,
    GetAllBoardsAndMainFolders: `${API_URL}/Boards/GetAllBoardsAndMainFolders`,
    GetAllBoardsAndChildFoldersByParentFolderId: `${API_URL}/Boards/GetAllBoardsAndChildFoldersByParentFolderId`,
    GetFolderById: `${API_URL}/Boards/GetFolderById`,
    GetAllFolders: `${API_URL}/Boards/GetAllFolders`,
    MoveFolderToFolder: `${API_URL}/Boards/MoveFolderToFolder`,
    MoveBoardToFolder: `${API_URL}/Boards/MoveBoardToFolder`,
    DeleteFolder: `${API_URL}/Boards/DeleteFolder`,
    UpdateFolder: `${API_URL}/Boards/UpdateFolder`,
    UpdateBoardStatuses: `${API_URL}/Boards/UpdateBoardStatuses`,
    DeleteBoardStatus: `${API_URL}/Boards/DeleteBoardStatus`,
  },

  JobAttachments: {
    GetAttachmentById: `${API_URL}/JobAttachments/GetAttachmentById`,
    GetAttachmentByJobId: `${API_URL}/JobAttachments/GetAttachmentByJobId`,
    GetAllAttachments: `${API_URL}/JobAttachments/GetAllAttachments`,
    CreateAttachment: `${API_URL}/JobAttachments/CreateAttachment`,
    UpdateAttachment: `${API_URL}/JobAttachments/UpdateAttachment`,
    DeleteAttachment: `${API_URL}/JobAttachments/DeleteAttachment`,
  },

  ContactPhotos: {
    GetPhotoById: `${API_URL}/ContactPhotos/GetPhotoById`,
    GetPhotosByContactId: `${API_URL}/ContactPhotos/GetPhotosByContactIdAsync`,
    GetAllPhotos: `${API_URL}/ContactPhotos/GetAllPhotosAsync`,
    AddContactPhoto: `${API_URL}/ContactPhotos/AddContactPhoto`,
    UpdateContactPhoto: `${API_URL}/ContactPhotos/UpdateContactPhotoAsync`,
    DeleteContactPhoto: `${API_URL}/ContactPhotos/DeleteContactPhotoAsync`,
    DownloadFiles: `${API_URL}/ContactPhotos/DownloadFiles`,
  },

  ContactAttachments: {
    GetAttachmentById: `${API_URL}/ContactAttachments/GetAttachmentById`,
    GetAttachmentByContactId: `${API_URL}/ContactAttachments/GetAttachmentByContactId`,
    GetAllAttachments: `${API_URL}/ContactAttachments/GetAllAttachments`,
    CreateAttachment: `${API_URL}/ContactAttachments/addContactAttachment`,
    UpdateAttachment: `${API_URL}/ContactAttachments/UpdateAttachment`,
    DeleteAttachment: `${API_URL}/ContactAttachments/DeleteAttachment`,
    DownloadFiles: `${API_URL}/ContactAttachments/DownloadFiles`,
  },

  Templates: {
    GetAllEmailTemplates: `${API_URL}/Templates/getAllEmailTemplates`,
    GetAllSMSTemplates: `${API_URL}/Templates/getAllSMSTemplates`,
    GetEmailTemplateById: `${API_URL}/Templates/email`,
    GetSMSTemplateById: `${API_URL}/Templates/sms`,
    CreateEmailTemplate: `${API_URL}/Templates/email/create`,
    CreateSMSTemplate: `${API_URL}/Templates/sms/create`,
    UpdateEmailTemplate: `${API_URL}/Templates/email/update`,
    UpdateSMSTemplate: `${API_URL}/Templates/sms/update`,
    DeleteEmailTemplate: `${API_URL}/Templates/email/delete`,
    DeleteSMSTemplate: `${API_URL}/Templates/sms/delete`,
},
  Automation: {
    GetAll: `${API_URL}/Automation/getall`,
    Delete: `${API_URL}/Automation/delete`,
    updateAutomationStatus: `${API_URL}/Automation/updateAutomationStatus`,
    Update: `${API_URL}/Automation/update`,
    Create: `${API_URL}/Automation/create`,
    GetById: `${API_URL}/Automation`,
  },

  AppConfigurations: {
    GetAll: `${API_URL}/AppConfigurations/getAll`,
    AddOrUpdateAppConfig: `${API_URL}/AppConfigurations/addOrUpdateAppConfig`,
    AddOrUpdateDashboardConfig: `${API_URL}/AppConfigurations/addOrUpdateDashboardConfig`,
    DeleteAppConfig: (id: number) => `${API_URL}/AppConfigurations/deleteAppConfig/${id}`,
    DeleteDashboardConfig: (id: number) => `${API_URL}/AppConfigurations/deleteDashboardConfig/${id}`,
  },
  
  DynamicFields: {
    Create: `${API_URL}/DynamicFields/create`,
    GetAllByEntityType: (entityType: string) => `${API_URL}/DynamicFields/${entityType}`,
    GetById: (id: string) => `${API_URL}/DynamicFields/field/${id}`,
    Update: `${API_URL}/DynamicFields/update`,
    Delete: (id: string) => `${API_URL}/DynamicFields/${id}`,
  },  

  Notification: {
    Send: `${API_URL}/Notification/send`,
    GetAll: `${API_URL}/Notification/getAll`,
    GetUnreadCount: `${API_URL}/Notification/getUnreadCount`,
    GetById: (id: string) => `${API_URL}/Notification/getById/${id}`,
    MarkAsRead: (id: string) => `${API_URL}/Notification/${id}/mark-read`,
    MarkAllAsRead: `${API_URL}/Notification/mark-all-read`,
    Delete: (id: string) => `${API_URL}/Notification/${id}`,
    DeleteAll: `${API_URL}/Notification/delete-all`,
  }
};
